<template>
  <div class="container">
    <q-item-label header class="text-h6">
      {{ name }}
    </q-item-label>
    <q-separator spaced inset />
    <div v-for="(layoutObj, layoutIndex) in layout" :key="layoutIndex">
      <div v-for="countIndex in layoutObj.count" :key="countIndex">
        <div v-for="(field, index) in layoutObj.data" :key="index">
          <toggle-setting
            v-if="field.type === 'toggle'"
            :name="field.name"
            :fieldName="field.fieldName"
            :description="field.description"
            :data-test="`toggle-setting-${index}`"
          />
          <pop-up-edit-setting
            v-if="field.type === 'popUpEdit'"
            :dataType="field.dataType"
            :name="field.name"
            :fieldName="field.fieldName"
            :hint="field.hint"
            :data-test="`popup-edit-setting-${index}`"
          />
          <drop-down-setting
            v-if="field.type === 'dropDown'"
            :name="field.name"
            :description="field.description"
            :fieldName="field.fieldName"
            :internalOptions="field.options"
            :data-test="`dropdown-setting-${index}`"
          />
          <multi-drop-down-setting
            v-if="field.type === 'multiDropDown'"
            :name="field.name"
            :description="field.description"
            :fieldName="field.fieldName"
            :internalOptions="field.options"
            :data-test="`multidropdown-setting-${index}`"
          />
        </div>
      </div>
    </div>
  </div>
</template>
<script lang="ts">
import ToggleSetting from '../../uiElements/ToggleSetting.vue';
import PopUpEditSetting from '../../uiElements/PopUpEditSetting.vue';
import DropDownSetting from '../../uiElements/DropDownSetting.vue';
import MultiDropDownSetting from '../../uiElements/MultiDropDownSetting.vue';
import AutoGenerated from './data/AutoGenerate.json';

export default {
  name: 'autoGenerate',
  components: {
    DropDownSetting,
    MultiDropDownSetting,
    ToggleSetting,
    PopUpEditSetting,
  },
  props: {},
  computed: {},
  data() {
    return {
      name: AutoGenerated.name,
      layout: AutoGenerated.layout,
    };
  },
};
</script>
