<template>
  <div class="container">
    <q-item-label header class="text-h6">
      {{ name }}
    </q-item-label>
    <q-separator spaced inset />
    <div v-for="(layoutObj, layoutIndex) in layout" :key="layoutIndex">
      <div v-for="countIndex in layoutObj.count" :key="countIndex">
        <div v-for="(field, index) in layoutObj.data" :key="index">
          <toggle-setting
            v-if="field.type === 'toggle'"
            :name="field.name"
            :fieldName="field.fieldName"
            :description="field.description"
            data-test="toggle-setting"
          />
          <pop-up-edit-setting
            v-if="field.type === 'popUpEdit'"
            :dataType="field.dataType"
            :name="field.name"
            :fieldName="field.fieldName"
            :hint="field.hint"
            data-test="popup-edit-setting"
          />
          <drop-down-setting
            v-if="field.type === 'dropDown'"
            :name="field.name"
            :description="field.description"
            :fieldName="field.fieldName"
            :internalOptions="internalOptions"
            data-test="dropdown-setting"
          />
        </div>
      </div>
    </div>
  </div>
</template>
<script>
import ToggleSetting from "../../uiElements/ToggleSetting.vue";
import PopUpEditSetting from "../../uiElements/PopUpEditSetting.vue";
import DropDownSetting from "../../uiElements/DropDownSetting.vue";
import AutoGenerated from "./data/AutoGenerate";

export default {
  name: "autoGenerate",
  components: {
    DropDownSetting,
    ToggleSetting,
    PopUpEditSetting,
  },
  props: {},
  computed: {},
  data() {
    return {
      name: AutoGenerated.name,
      layout: AutoGenerated.layout,
      internalOptions: [
        { label: "Option 1", value: 1 },
        { label: "Option 2", value: 2 },
        { label: "Option 3", value: 3 },
      ],
    };
  },
};
</script>
