import AutoGeneratedPage from '../../../src/components/AutoGenerate/AutoGenerate.vue'; // <= note the absence of `.vue` extension, here we are importing the JS/TS part of a Double File Component
describe('AutoGenerated Page tests', () => {
  it('Auto generated page from JSON should contain all the UI Elements', () => {
    cy.mount(AutoGeneratedPage);
    cy.get('[data-test="toggle-setting-0"]').invoke('val').should('eq', false);
    cy.get('[data-test="toggle-setting-0"]').focus().click();
    cy.get('[data-test="toggle-setting-0"]').invoke('val').should('eq', true);
    /*
    expect(popUpEdit.props().hint).toEqual("Popup Edit box hint");
    const popUpEditNumber = autoGenerate.findComponent('[data-test="popup-edit-setting-2"]');
    expect(popUpEditNumber.exists()).toBeTruthy();
    expect(popUpEditNumber.props().hint).toEqual("Popup Edit box (Number) hint");
    expect(popUpEditNumber.props().dataType).toEqual("number");
    const dropDown = autoGenerate.findComponent('[data-test="dropdown-setting-3"]');
    expect(dropDown.exists()).toBeTruthy();
    expect(autoGenerate.vm.internalOptions.length).toEqual(3);
    */
   cy.get('[data-test="dropdown-setting-3"]').should('have.text', 'Option 1');
   cy.get('[data-test="dropdown-setting-3"]').should('have.text', 'Option 2');
   cy.get('[data-test="dropdown-setting-3"]').should('have.text', 'Option 3');
  });
})