<template>
  <q-page padding>
    <auto-generate :optionsMap="optionsMap" data-test="auto-generate" />
  </q-page>
</template>
<script>
import { defineComponent, ref } from 'vue';
import AutoGenerate from '../components/AutoGenerate/AutoGenerate.vue';
export default defineComponent({
  name: 'AutoGeneratedPage',
  components: { AutoGenerate },
  data: function () {
    return {
      optionsMap: {},
    };
  },
});
</script>
