<template>
  <q-page padding>
    <auto-generate :optionsMap="optionsMap" />
  </q-page>
</template>
<script>
import { defineComponent, ref } from "vue";
import AutoGenerate from "../components/AutoGenerate/AutoGenerate";
export default defineComponent({
  name: "AutoGeneratedPage",
  components: { AutoGenerate },
  data: function () {
    return {
      optionsMap: {},
    };
  },
});
</script>
