name: Quasar Application CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: branch
      - name: Install CLIs
        run: |
          sudo npm install -g firebase-tools
          sudo npm install -g @quasar/cli
      - name: Build
        run: npm install
      - name: Deploy
        run: npm run deploy
#      - name: Firebase Deploy
#        if: steps.branch.outputs.branch == 'master'
#        run: firebase deploy -P production --token ${{ secrets.FIREBASE_TOKEN }} --only hosting
#  slack-notification:
#    name: Slack Notification
#    runs-on: ubuntu-latest
#    needs: build-and-deploy
#    steps:
#      - uses: actions/checkout@v2
#      - name: Slack Notification
#        uses: rtCamp/action-slack-notify@v2
#        env:
#          SLACK_CHANNEL: tech-github
#          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
#          SLACK_ICON: https://github.com/khteh.png?size=48
#          SLACK_TITLE: "INTERNAL deployed to ${{ steps.branch.outputs.branch == 'staging' && 'staging' || 'production' }} successfully!"
#          SLACK_USERNAME: khteh
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
