name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: branch
      - name: Remove existing Node.JS
        run: sudo apt remove -y nodejs
      - name: Install specific version of Node.JS
        run: |
          curl -s -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
          . ~/.bashrc
          nvm install 10.23.0
      - name: Install CLIs
        run: |
          sudo npm install -g firebase-tools
          sudo npm install -g @quasar/cli
      - name: Build
        run: |
          npm install
          quasar build
      - name: Firebase Deploy
        if: steps.branch.outputs.branch == 'master'
        run: firebase deploy -P production --token ${{ secrets.FIREBASE_TOKEN }} --only hosting
#  slack-notification:
#    name: Slack Notification
#    runs-on: ubuntu-latest
#    needs: build-and-deploy
#    steps:
#      - uses: actions/checkout@v2
#      - name: Slack Notification
#        uses: rtCamp/action-slack-notify@v2
#        env:
#          SLACK_CHANNEL: tech-github
#          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
#          SLACK_ICON: https://github.com/qashier.png?size=48
#          SLACK_TITLE: "INTERNAL deployed to ${{ steps.branch.outputs.branch == 'staging' && 'staging' || 'production' }} successfully!"
#          SLACK_USERNAME: qashier
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
